# Service account with IRSA annotation
# This gives backend pods scoped access to Secrets Manager only
# No other pods get these permissions
# Satisfies REQ-NCA-P3-06 Zero Trust - least privilege at pod level
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hr-backend-sa
  namespace: hr-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::985738120856:role/case-study-hr-backend-irsa